name: JoinPrivileges
version: 2.0.0
api-version: 1.13
description: A modern Join/Leave plugin for Spigot
main: me.omegaweapondev.joinprivileges.JoinPrivileges

author: OmegaWeaponDev

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  joinprivileges:
    description: The core command for the JoinPrivileges plugin
    aliases: [jp, joinp, jprivileges]
  joineffects:
    description: The join effects command
    aliases: [je, jeffects, joine]
  maintenance:
    description: The maintenance mode command
    aliases: [jpm, mm]
  playtime:
    description: The playtime command
    aliases: [play, playt, ptime, pt]
  rewards:
    description: The rewards command
    aliases: [jprewards, joinprivilegesrewards, joinrewards, jr, jpr]

permissions: {}
