name: ${project.name}
version: ${project.version}
api-version: ${pl.apiver}
description: ${project.description}
main: ${main.class}

author: ${pl.author}

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  joinprivileges:
    description: The core command for the JoinPrivileges plugin
    aliases: [jp, joinp, jprivileges]
  joineffects:
    description: The join effects command
    aliases: [je, jeffects, joine]
  maintenance:
    description: The maintenance mode command
    aliases: [jpm, mm]
  playtime:
    description: The playtime command
    aliases: [play, playt, ptime, pt]
  rewards:
    description: The rewards command
    aliases: [jprewards, joinprivilegesrewards, joinrewards, jr, jpr]

permissions: {}
