name: JoinPrivileges
version: 2.0.0
api-version: 1.13
description: A modern Join/Leave plugin for Spigot
main: me.omegaweapondev.joinprivileges.JoinPrivileges

author: OmegaWeaponDev

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  joinprivileges:
    description: The core command for the JoinPrivileges plugin
    aliases: [jp, joinp, jprivileges]
  joineffects:
    description: The join effects command
    aliases: [je, jeffects, joine]
  maintenance:
    description: The maintenance mode command
    aliases: [jpm, mm]
  playtime:
    description: The playtime command
    aliases: [play, playt, ptime, pt]
  rewards:
    description: The rewards command
    aliases: [jprewards, joinprivilegesrewards, joinrewards, jr, jpr]

permissions:
  joinprivileges.admin:
    description: The wildcard permission that grants all the permissions for the plugin.
    default: false
    children:
      - joinprivileges.reload
      - joinprivileges.debug
      - joinprivileges.update
      - joinprivileges.maintenance.toggle
      - joinprivileges.maintenance.bypass
  joinprivileges.reload:
    description: The permission required to reload the plugin.
    default: false
  joinprivileges.debug:
    description: The permission required to run the debug command.
    default: false
  joinprivileges.update:
    description: The permission required to recieve the update notifications.
    default: false
  joinprivileges.maintenance.toggle:
    description: The permission required to toggle the maintenance mode status.
    default: false
  joinprivileges.maintenance.bypass:
    description: The permission required to bypass the maintenance mode join block
    default: false
